###
# Application example
###

kind: Deployment
apiVersion: apps/v1
metadata:
  labels:
    cluster: management
    component: login-api
  name: login-api
  namespace: nalej
spec:
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      cluster: management
      component: login-api
  template:
    metadata:
      labels:
        cluster: management
        component: login-api
    spec:
      containers:
      - name: login-api
        image: nalejregistry.azurecr.io/nalej/login-api:VERSION
        imagePullPolicy: Always
        args:
        - "run"
        - "--debug"
        - "--authxAddress=authx.nalej:8810"
        securityContext:
          runAsUser: 2000
      imagePullSecrets:
      - name: nalej-registry
