###
# Application example
###

kind: Deployment
apiVersion: apps/v1
metadata:
  labels:
    cluster: management
    component: login-api
  name: login-api
  namespace: __NPH_NAMESPACE
spec:
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      cluster: management
      component: login-api
  template:
    metadata:
      labels:
        cluster: management
        component: login-api
    spec:
      containers:
        - name: login-api
          image: __NPH_REGISTRY/__NPH_REGISTRY_NAMESPACE/login-api:__NPH_VERSION
          imagePullPolicy: Always
          args:
            - "run"
            - "--authxAddress=authx.__NPH_NAMESPACE:8810"
          securityContext:
            runAsUser: 2000
      imagePullSecrets:
        - name: nalej-registry
