kind: Service
apiVersion: v1
metadata:
  name: login-api
  labels:
    cluster: management
    component: login-api
  namespace: nalej
spec:
  selector:
    cluster: management
    component: login-api
  type: ClusterIP
  ports:
  - protocol: TCP
    name: grpc
    port: 8444
    targetPort: 8444
  - protocol: TCP
    name: http
    port: 8443
    targetPort: 8443